### ISSUE TITLE
Race conditions in InMemoryStore

### ISSUE THREAD

**Issue by radaczynski** [clun/ff4j#121]
There is no synchronization on the auto creation of the features in InMemoryStore (possibly others too), whic manifests itself in:

`Caused by: org.ff4j.exception.FeatureAlreadyExistException: featureid already exist in store, duplicate uid
        at org.ff4j.store.InMemoryFeatureStore.create(InMemoryFeatureStore.java:143)
        at org.ff4j.FF4j.getFeature(FF4j.java:356)
        at org.ff4j.FF4j.check(FF4j.java:137)
        at org.ff4j.FF4j.check(FF4j.java:124)
        at org.ff4j.aop.FeatureAdvisor.shouldFlip(FeatureAdvisor.java:173)
        at org.ff4j.aop.FeatureAdvisor.invoke(FeatureAdvisor.java:74)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
`

I suppose that synchronizing the creation [wrapping this line in synchronized(this)](https://github.com/clun/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/FF4j.java#L420) would solve it, I guess. Either that or ignoring the existance of a feature in the store implementaion itself in the create method.

**Comment by clun** [comment]
I reproduces this - not so easy (AOP + autoCreate). Wrapping the create() operation with  `synchronize` alone won't do the trick. 

It's the `FF4J.getFeature` that must to be synchronized (the autocreate is also caried by the FF4J class) and avoid double creation.

Will be part of 1.5.1, released probably by end of this month.

**Comment by radaczynski** [comment]
yup, after swtichign to the new release, I don't see the errors anymore. Thanks for fixing this!

**Comment by kubked** [comment]
Hi, I have met the same issue with version 1.6.5. Please look at the attached stacktrace:
```
org.ff4j.exception.FeatureAlreadyExistException: featureName already exist in store, duplicate uid
	at org.ff4j.store.AbstractFeatureStore.assertFeatureNotExist(AbstractFeatureStore.java:291)
	at org.ff4j.store.InMemoryFeatureStore.create(InMemoryFeatureStore.java:138)
	at org.ff4j.FF4j.getFeature(FF4j.java:432)
	at org.ff4j.FF4j.check(FF4j.java:177)
	at org.ff4j.FF4j.check(FF4j.java:164)
```

I see you removed ```synchronized``` in commit [```e1f7a72fe518603d93a713805cb801aa7e3532c6```.](https://github.com/ff4j/ff4j/commit/e1f7a72fe518603d93a713805cb801aa7e3532c6#diff-d9709a46f9cc2d52fa38101233089ba6L420) Is there a chance to get it back, please?
