### ISSUE TITLE
ff4j load ff4j.xml exception

### ISSUE THREAD

**Issue by lijunyong** [clun/ff4j#216]
```
<bean id="ff4j" class="org.ff4j.FF4j">
	<constructor-arg index="0" type="java.lang.String" value="classpath*:ff4j.xml"/>
</bean>
```

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ff4j.FF4j]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Cannot parse feature stream
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 55 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot parse feature stream
	at org.ff4j.store.InMemoryFeatureStore.loadConf(InMemoryFeatureStore.java:102)
	at org.ff4j.store.InMemoryFeatureStore.loadConfFile(InMemoryFeatureStore.java:91)
	at org.ff4j.store.InMemoryFeatureStore.<init>(InMemoryFeatureStore.java:58)
	at org.ff4j.FF4j.<init>(FF4j.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 57 common frames omitted
```

**Comment by bobpaige** [comment]
I'm seeing this today as well. I have my dependencies set to download the most recent version ("1.+") which may be why I did not see this earlier in the week.

@lijunyong , what version are you running?

**Comment by lijunyong** [comment]
@bobpaige 
```
<dependency>
			<groupId>org.ff4j</groupId>
			<artifactId>ff4j-web</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.ff4j</groupId>
			<artifactId>ff4j-aop</artifactId>
			<version>1.6.2</version>
		</dependency>
		<dependency>
			<groupId>org.ff4j</groupId>
			<artifactId>ff4j-core</artifactId>
			<version>1.6.2</version>
		</dependency>
```

**Comment by clun** [comment]
Hello,

From 1.6.1 to 1.6.2 I has to strengthen the XML parser to prevent XML Injection. Now everything is strongly validated where it was not the case before.

Could you please give us the ff4j.xml I can correct it for you. 

You can also directly test the parsing with :
```java
 InputStream in = getClass().getClassLoader().getResourceAsStream("test-featureXmlParserTest-ok.xml");
  Map<String, Feature> features = new XmlParser().parseConfigurationFile(in).getFeatures();
```

Please here a working sample:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ff4j xmlns="http://www.ff4j.org/schema/ff4j" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:schemaLocation="http://ff4j.org/schema/ff4j-1.6.xsd">
	<features>
		<feature uid="AwesomeFeature" enable="true" description="some desc"/>
		<feature uid="first" enable="true" description="description">
			<security>
				<role name="USER"/>
			</security>
			<custom-properties>
				<property name="ppint" value="12"/>
				<property name="ppdouble" value="12.5"/>
				<property name="ppboolean" value="true"/>
				<property name="ppstring" value="hello"/>
				<property name="ppListInt" value="12,13,14"/>
				<property name="myLogLevel" value="DEBUG" type="org.ff4j.property.PropertyLogLevel"/>
				<property name="digitValue" value="1" type="org.ff4j.property.PropertyInt">
					<fixedValues>
						<value>0</value>
						<value>1</value>
						<value>2</value>
						<value>3</value>
					</fixedValues>
				</property>
				<property name="regionIdentifier" value="AMER">
					<fixedValues>
						<value>AMER</value>
						<value>SSSS</value>
						<value>EAST</value>
						<value>EAST</value>
					</fixedValues>
				</property>
			</custom-properties>
		</feature>
		<feature-group name="GRP0">
			<feature uid="second" enable="false" description="description">
				<security>
					<role name="USER"/>
				</security>
			</feature>
		</feature-group>
		<feature-group name="GRP1">
			<feature uid="forth" enable="true" description="description">
				<flipstrategy class="org.ff4j.strategy.el.ExpressionFlipStrategy">
					<param name="expression" value="third | second"/>
				</flipstrategy>
				<security>
					<role name="ADMINISTRATOR"/>
					<role name="BETA-TESTER"/>
				</security>
			</feature>
			<feature uid="third" enable="false">
				<security>
					<role name="ADMINISTRATOR"/>
					<role name="BETA-TESTER"/>
				</security>
			</feature>
		</feature-group>
	</features>
	<properties>
		<property name="a" value="AMER" description="Sample">
			<fixedValues>
				<value>AMER</value>
				<value>EAST</value>
				<value>EAST</value>
				<value>EAST</value>
			</fixedValues>
		</property>
		<property name="b" value="12"/>
		<property name="c" value="12.5"/>
		<property name="d" value="true"/>
		<property name="e" value="hello"/>
		<property name="f" value="12,13,14"/>
		<property name="g" value="DEBUG" type="org.ff4j.property.PropertyLogLevel"/>
	</properties>
</ff4j>

```

**Comment by lijunyong** [comment]
@clun 
application-aop.xml
```
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans-3.0.xsd http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd">

	<context:component-scan base-package="org.ff4j.aop, com.omniprimeinc.component.eureka.test" />

	<bean id="ff4j" class="org.ff4j.FF4j">
	</bean>
</beans>
```
ff4j.xml
```
<?xml version="1.0" encoding="UTF-8" ?>
<features>
	<feature uid="language-french" enable="false" />
</features>
```
```

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:application-spring.xml"})
public class FF4jTest {
   

    @Autowired
    @Qualifier("greeting.english")
    private GreetingService greeting;
    
    @Autowired
    private FF4j ff4j;

    @Test
    public void testAOP() {
        InputStream is = null;
        try {
            is = new FileInputStream("G:\\projects\\eureka-zuul\\src\\main\\resources\\ff4j.xml");
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        ff4j.setFeatureStore(new InMemoryFeatureStore(is));
        System.out.println(greeting.sayHello("CLU"));
        ff4j.enable("language-french");
        System.out.println(greeting.sayHello("CLU"));
    }
}
```
it's success.but the  config throw exception, FF4j class constructor support  xml path

```
    public FF4j(String xmlFile) {
        this.fstore = new InMemoryFeatureStore(xmlFile);
        this.pStore = new InMemoryPropertyStore(xmlFile);
    }

<bean id="ff4j" class="org.ff4j.FF4j">
	<constructor-arg index="0" type="java.lang.String" value="classpath*:ff4j.xml"/>
</bean>
```

**Comment by clun** [comment]
Well, I reproduced the problem easily.

With your bean definition 
```xml
<bean id="ff4j" class="org.ff4j.FF4j">
	<constructor-arg index="0" type="java.lang.String" value="classpath*:ff4j.xml"/>
</bean>
```
just do :
```java
new ClassPathXmlApplicationContext("applicationContext-test.xml").getBean("ff4j");
```

The *problem* is that FF4j is not strongly coupled to the Spring framework. The string expected in `FF4j`class constructor is the full or relative path of `ff4j.xml` file.

Here you put `classpath:` in front of it which is not a valid path; it's a Spring syntax. It should have worked if we used a `Resource` as attribute but it's not the case.

Find some elements [here](http://stackoverflow.com/questions/15297557/loading-a-file-from-classpath)

Consider a wrapper ?

```java
 public static class FF4JSpringWrapper {
        
        private FF4j ff4j;
        
        public FF4JSpringWrapper(Resource cf) {
            try {
                ff4j = new FF4j(cf.getInputStream());
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        
    };
```
