### ISSUE TITLE
Spring Boot 1.5 with FF4J starter fail to start 

### ISSUE THREAD

**Issue by damienbeaufils** [clun/ff4j#251]
## Issue
When creating a new Spring Boot project (using Spring initializr) and adding the `ff4j-spring-boot-starter` 1.6.5 dependency, the application fails to start with this stacktrace: 
```
java.lang.NoSuchMethodError: com.fasterxml.classmate.TypeBindings.withAdditionalBinding(Ljava/lang/String;Lcom/fasterxml/classmate/ResolvedType;)Lcom/fasterxml/classmate/TypeBindings;
	at springfox.documentation.schema.WildcardType.adjustedTypeBindings(WildcardType.java:137) ~[springfox-core-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.WildcardType.breadthFirstSearch(WildcardType.java:117) ~[springfox-core-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.WildcardType.collectReplaceables(WildcardType.java:74) ~[springfox-core-2.2.2.jar:2.2.2]
	at springfox.documentation.schema.AlternateTypeRule.alternateFor(AlternateTypeRule.java:50) ~[springfox-core-2.2.2.jar:2.2.2]
	at springfox.documentation.spi.schema.AlternateTypeProvider.alternateFor(AlternateTypeProvider.java:44) ~[springfox-spi-2.2.2.jar:2.2.2]
	at springfox.documentation.spi.service.contexts.RequestMappingContext.alternateFor(RequestMappingContext.java:118) ~[springfox-spi-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.collectFromReturnType(OperationModelsProvider.java:70) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.readers.operation.OperationModelsProvider.apply(OperationModelsProvider.java:59) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.modelContexts(DocumentationPluginsManager.java:129) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiModelReader.read(ApiModelReader.java:62) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiListingScanner.scan(ApiListingScanner.java:91) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:62) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:87) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.onApplicationEvent(DocumentationPluginsBootstrapper.java:50) ~[springfox-spring-web-2.2.2.jar:2.2.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
```

It seems that the used springfox-swagger version search for an old version of jackson-databind

## Steps to reproduce
* Go to [start.spring.io](https://start.spring.io/) 
* Create a new project with current Spring Boot version (1.5.6)
* Add `ff4j-spring-boot-starter` dependency in build.gradle or pom.xml
* Run the spring boot application

## Workaround
Override **`springfox-swagger2`** and **`springfox-swagger-ui`** versions in `build.gradle` or `pom.xml` to use the last version.
Example with a `build.gradle` file, add those lines:
```
	compile 'io.springfox:springfox-swagger2:2.7.0'
	compile 'io.springfox:springfox-swagger-ui:2.7.0'
```

**Comment by clun** [comment]
I débug this incident on gitter please have a look : there is an invalid dependency in spring boot 1.5, Dave Syer looked at it. You can fix it with the POM.

**Comment by clun** [comment]
Spriing boot drag so many dependencies sometimes hard to tell, with the same parent different behavior. Will please enforce SpringFox to 1.5.°

```xml
<dependency>
 <groupId>io.springfox</groupId>
 <artefactId>springfox-spi</artefactId>
 <version>2.5.0</version>
</dependency>
```

**Comment by damienbeaufils** [comment]
Thanks @clun 
We'll see if it's better when Spring Boot 2.0 will be released!

**Comment by clun** [comment]
Will now close this issue, workaround have been provided.

**Comment by f0r3v3ran00b** [comment]
Thanks so much, all!
