### ISSUE TITLE
Ehcache issue

### ISSUE THREAD

**Issue by abuinteam** [clun/ff4j#266]
Hi Clun,

Thanks for your response. I added the below dependency and also encache. But I am getting the NoClassDefFoundError from FeatureCacheProviderEhCache.initializeCache. I have all the required dependencies. Am i missing something?

ff4j-store-ehcache (version 1.6.5) and also ehcache in my classpath

FF4J cofiguration:
FF4j ff4j = new FF4j();
        FF4JCacheManager ff4jCacheManager = new FeatureCacheProviderEhCache();
        ff4j.setFeatureStore(new FeatureStoreSpringJdbc(dataSource));
        ff4j.setPropertiesStore(new PropertyStoreSpringJdbc(dataSource));
        ff4j.setEventRepository(new EventRepositorySpringJdbc(dataSource));
        ff4j.autoCreate(true);
        ff4j.audit(true);
        ff4j.cache(ff4jCacheManager);
        return ff4j;

Caused by: java.lang.NoClassDefFoundError: net/sf/ehcache/CacheManager
	at org.ff4j.cache.FeatureCacheProviderEhCache.initializeCache(FeatureCacheProviderEhCache.java:86) ~[ff4j-store-ehcache-1.6.5.jar:1.6.5]
	at org.ff4j.cache.FeatureCacheProviderEhCache.getCacheFeatures(FeatureCacheProviderEhCache.java:184) ~[ff4j-store-ehcache-1.6.5.jar:1.6.5]
	at org.ff4j.cache.FeatureCacheProviderEhCache.getFeature(FeatureCacheProviderEhCache.java:141) ~[ff4j-store-ehcache-1.6.5.jar:1.6.5]
	at org.ff4j.cache.FF4jCacheProxy.exist(FF4jCacheProxy.java:109) ~[ff4j-core-1.6.5.jar:1.6.5]
	at org.ff4j.spring.autowire.AutowiredFF4JBeanPostProcessor.readFeature(AutowiredFF4JBeanPostProcessor.java:190) ~[ff4j-aop-1.6.5.jar:1.6.5]
	at org.ff4j.spring.autowire.AutowiredFF4JBeanPostProcessor.autoWiredFeature(AutowiredFF4JBeanPostProcessor.java:113) ~[ff4j-aop-1.6.5.jar:1.6.5]
	at org.ff4j.spring.autowire.AutowiredFF4JBeanPostProcessor.postProcessAfterInitialization(AutowiredFF4JBeanPostProcessor.java:84) ~[ff4j-aop-1.6.5.jar:1.6.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: net.sf.ehcache.CacheManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 25 common frames omitted

**Comment by clun** [comment]
Hum if i dig into :

- ff4j-store-ehcache (Ehcache2X), all should be there because I have...

```xml
<dependency>
 <groupId>net.sf.ehcache</groupId>
 <artifactId>ehcache</artifactId>
</dependency>
```
Or

- ff4j-store-jcache    ===> JSR107 ==> EHCACHE3

```java
// JCACHE APPROACH
import org.ehcache.jsr107.EhcacheCachingProvider;
[..]
FF4JCacheManager ff4jCacheManager = new FF4jJCacheManager(EhcacheCachingProvider.class.getName());
```
and you have to explicitely add ehcache as dependency (more generic store)

**Comment by abuinteam** [comment]
Hi Clun, 

This is working fine.

**Comment by dzmitryh** [comment]
thanks @clun it helped. But does anyone know how to force /metrics/cache.gets/ to increment their values. Everything is fine but cache statistics looks like is missing
