### ISSUE TITLE
Question about FeatureTagEnable

### ISSUE THREAD

**Issue by hlassiege** [clun/ff4j#71]
Hi,

I'm running a benchmark on our application and I found a place that looks weird at the first place in FeatureTagEnable : 

executionContext.putString("LOCALE", pageContext.getRequest().getLocalName());

This is the full stack trace : 

```
http-nio-8087-exec-173@13802" daemon prio=5 tid=0x14e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.Inet6AddressImpl.getHostByAddr(Inet6AddressImpl.java:-1)
	  at java.net.InetAddress$2.getHostByAddr(InetAddress.java:932)
	  at java.net.InetAddress.getHostFromNameService(InetAddress.java:617)
	  at java.net.InetAddress.getHostName(InetAddress.java:559)
	  at java.net.InetAddress.getHostName(InetAddress.java:531)
	  at org.apache.coyote.http11.Http11NioProcessor.actionInternal(Http11NioProcessor.java:341)
	  at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:919)
	  at org.apache.coyote.Request.action(Request.java:379)
	  at org.apache.catalina.connector.Request.getLocalName(Request.java:1277)
	  at org.apache.catalina.connector.RequestFacade.getLocalName(RequestFacade.java:989)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at javax.servlet.ServletRequestWrapper.getLocalName(ServletRequestWrapper.java:326)
	  at org.ff4j.web.taglib.FeatureTagEnable.eval(FeatureTagEnable.java:52)
	  at org.ff4j.web.taglib.AbstractFeatureTag.doStartTag(AbstractFeatureTag.java:86)
```

Each time this is called, there is a Inet6AddressImpl.getHostByAddr called and it's quite costly.

What is the point of having the host name ?

**Comment by clun** [comment]
This was for implementing a *FlippingStrategy* based on Locale. All parameters available in the WebSession become available in the execution context.

I agree that it's time consuming and **shouldn't be a default behaviour**. What about disabling by default and add an optional parameter to the tag enable to enforce.
```
<ff4j:enable featureid="xxxx" shareHttpSession="true" />

I you're fine I'll do with the update. 

PS I'm currently working on ff4j-web to slip embedded servlet/taglib from REST API.

**Comment by hlassiege** [comment]
I'm not sure to understand :)
In the executionContext, this code put the host name, which is quite confusing for me.

But I'm agree, it shouldn't be a default behaviour, especially because I can use ff4j in jobs and not in a request.
Moreover, if I need some information about the request, I prefer to use this kind of code in the strategy : 

ServletRequestAttributes sra = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();

(but it's only in Spring of course)

**Comment by clun** [comment]
This code put indeed the hostname, and just below in the same class  i put all the request attributes.

I will update the TAG

**Comment by clun** [comment]
v1.3.5 is released tonight and fix it.
